export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  PENDING = 'PENDING',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  SENTIMENT_FAILED = 'SENTIMENT_FAILED',
  TRANSLATION_FAILED = 'TRANSLATION_FAILED',
}
